name: "beszel"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  hub:
    image: "11notes/beszel:0.15.2"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "hub.var:/beszel/var"
    ports:
      - "3000:8090/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  hub.var:

networks:
  frontend: